### ISSUE TITLE
Extension crashes vscode when used inside remote container

### ISSUE THREAD

**Issue by ljubadr** [ctf0/laravel-goto-config#5]
Hi again! I've recently asked you [to add option to specify php path](https://github.com/ctf0/laravel-goto-config/issues/4) so that extension could work with docker and it works really well

Since then I did a bit of research and I found out that [vscode remote containers](https://code.visualstudio.com/docs/remote/containers) fit my needs better since most of the other vscode/laravel extensions work out of the box without any additional path configuration or in some cases even ugly hacks

Now I have new issue with this extension. It only happens when it's used inside the remote docker container. If I click on the config link, vscode crashes and restarts right away. I tried to find crash error message or any kind of logs that I could post here. I used `Developer: Open log folder...` and I searched the log files but I didn't manage to find anything useful... I don't know enough about developing vscode extensions to debug this :smile:

This extension works nicely directly on the computer or when I specify the path to the docker php executable. But something is making the click crash vscode. Same things also happens with your extension `goto-env`. It might be even issue with `remote containers` in vscode and how it handles `new DocumentLink`.

When I hover on the `config('app.name')` link shows `vscode://ctf0.laravel-goto-config/var/www/html/config/app.php?name`

![image](https://user-images.githubusercontent.com/13367907/159188010-c8b545af-6999-47d7-a5c4-93a8375e0280.png)

Note: absolute path to laravel project inside the docker is `/var/www/html/` and I tested with default settings (double checked all `settings.json` files)

This crash happens on 2 different computers that I've tested on - macbook pro (intel) and ubuntu 20.04

I've created the [repository](https://github.com/ljubadr/laravel-goto-config-remote-container-crash) to help reproduce the error

It's basic laravel install with laravel sail and devcontainers. Steps are in the readme. Let me know if you want me to provide more info or test the update

**Comment by ljubadr** [comment]
I just tested going directly to `vscode://ctf0.laravel-goto-config/var/www/html/config/app.php?name` while the vscode is opened in remote container and it also crashes

It looks like it could be crashing in [registerUriHandler](https://github.com/ctf0/laravel-goto-config/blob/cdbe6344d8f33b96148462a1197ae42d247389c8/src/util.ts#L120)

**Comment by ctf0** [comment]
sadly i have no experiance with `remote containers` and therfore i cant help with this one, basically what the ext does is parsing the config key into a path then try to navigate to it, so anything different than that wont work.

maybe as a way around i would check for remote containers mode (if that is even possible) and disable the ext

**Comment by ljubadr** [comment]
I've posted to [stackoverflow](https://stackoverflow.com/questions/71560395/is-it-possible-to-use-documentlink-and-registerurihandler-when-using-the-remote) and I've tagged with `vscode-remote` and I hope I'll get some answers

In the meantime I was looking for examples where links do actually work and I found this example

![devcontainer json 2022-03-21 14-50-26](https://user-images.githubusercontent.com/13367907/159343634-44d82e6d-4e59-4dc2-8b64-4c705f6a19ab.png)

Link that get's generated is

```
vscode-remote://dev-container+2f55...../var/www/api/.devcontainer/docker-compose.extend.yml
```

So it probably means that while using `remote containers` extension generated links would need to be in slightly different format

**Comment by ctf0** [comment]
for the `vscode-remote://` part i think i can find out and add it when needed via https://code.visualstudio.com/api/references/vscode-api#env, however still missing how to for 
- how to get the `dev-container` part.
- how to debug the changes

**Comment by ljubadr** [comment]
I found this docs - [Callbacks and URI handlers](https://code.visualstudio.com/api/advanced-topics/remote-extensions#callbacks-and-uri-handlers)

> The Remote Development and Codespaces extensions in VS Code will transparently handle passing the URI to your extension regardless of where it is actually running (local or remote)

It looks like it should work out of the box without the need to change anything. I think that `vscode-remote://` is used if there is not extension to handle that URI, which is not the case with your extension

---

I think I managed to pinpoint the issue. I opened extension files in the remote container that are located in folder

```
/home/laradock/.vscode-server/extensions/ctf0.laravel-goto-config-0.2.7/
```

and then investigated what happens around this line

```
vscode_1.commands.executeCommand('vscode.openFolder', vscode_1.Uri.file(path))
```

I found out that `vscode.openFolder` is actually causing a "crash". It looks like that vscode is not crashing but opening folder which causes remote containers to "crash" and restart vscode even if it's the same folder. I guess this works on host without causing issues

I found info In [this docs](https://code.visualstudio.com/api/references/commands)

> vscode.openFolder - Open a folder or workspace in the current window or new window depending on the newWindow argument. Note that opening in the same window will shutdown the current extension host process and start a new one on the given folder/workspace unless the newWindow parameter is set to true.

I changed this value to `vscode.open` and reloaded the editor and now when I click config it actually jumped to the config file without the "crash". I didn't test this on my host computer to see if it causes issues when extension is used directly

So this solves the issue

```
vscode_1.commands.executeCommand('vscode.open', vscode_1.Uri.file(path))
```

> vscode.open - Opens the provided resource in the editor. Can be a text or binary file, or an http(s) URL. If you need more control over the options for opening a text file, use vscode.window.showTextDocument instead.
> - uri - Uri of a text document
> -  columnOrOptions - (optional) Either the column in which to open or editor options, see vscode.TextDocumentShowOptions
> - label - (optional)
> - (returns) - no result

**Comment by ctf0** [comment]
u r correct, `openfolder` wasnt the right command to use from the beginning, try the new versions for all the goto pkgs it should be fixed now.

big thanks for the headsup and detailed investigation.❤️

**Comment by ljubadr** [comment]
I didn't mind digging deeper to find the issue. I was planning on learning developing vscode extensions so this is a nice way to get my feet wet 😄 

I've tested all goto extensions

These work after update and there are no more "crashes"
- goto config
- goto path
- goto view

These didn't work before and they still don't work in remote containers (but they work on host). They don't show links that I can click on
- goto lang
- goto env
- goto controller

I'll have to test a bit more and I'll create new issues in those repos once I make sure that it's not related to my current legacy project . Now that I have [test github project](https://github.com/ljubadr/laravel-goto-config-remote-container-crash) I'll check with that and I'll report back

Thanks again for the fast response and thank you for developing these cool goto extensions that save time and make developing laravel so much easier 👍
